2019 09 cm pb 68
TRESCLOUD/server-tools pull request #36
Opened 2019-09-23 17:33 UTC by rquevedo

2019-09-23 22:43 UTC, pepetreshere requested changes

2019-09-23 22:43 UTC, pepetreshere commented on base_export_security/i18n/es.po
> +msgid "Right Margin (mm)"
estas cosas son de otros modulos!

2019-09-23 22:43 UTC, pepetreshere commented on base_export_security/i18n/es.po
> +msgstr "Este código va ser usado para generar el cash management del banco bolivariano, debe tener 6 digitos."
estas cosas son de otros modulos

2019-09-24 15:31 UTC, rquevedo commented on base_export_security/i18n/es.po
> +msgid "Right Margin (mm)"
ok

2019-09-24 15:31 UTC, rquevedo commented on base_export_security/i18n/es.po
> +msgstr "Este código va ser usado para generar el cash management del banco bolivariano, debe tener 6 digitos."
ok

2019-09-26 04:13 UTC, pepetreshere requested changes

2019-09-26 04:13 UTC, pepetreshere commented on auth_brute_force/controllers/__init__.py
> +from . import main
Hagamos un extra en este módulo, en el form de usuario agregar (programar en el mismo módulo de la OCA):
- botón para desbloquear el usuario (o expliquenme como desbloqueo)
- botón para ver intentos de login (modelo res.authentication.attempt), ojo ya existe el menú

2019-09-26 15:09 UTC, rquevedo commented on auth_brute_force/controllers/__init__.py
> +from . import main
Hecho

2019-09-26 23:48 UTC, pepetreshere approved these changes

2019-09-26 23:48 UTC, merged